backend:
  name: git-gateway
  branch: chore/7-add-cms # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/images/uploads
i18n:
  # Required and can be one of multiple_folders, multiple_files or single_file
  # multiple_folders - persists files in `<folder>/<locale>/<slug>.<extension>`
  # multiple_files - persists files in `<folder>/<slug>.<locale>.<extension>`
  # single_file - persists a single file in `<folder>/<slug>.<extension>`
  structure: multiple_folders

  # Required - a list of locales to show in the editor UI
  locales: [en, cy]

  # Optional, defaults to the first item in locales.
  # The locale to be used for fields validation and as a baseline for the entry.
  default_locale: en

collections:
  - name: i18n_content
    i18n: true
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt text", name: "alt", widget: "string" }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "guides"
    label: "Guides"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Summary", name: sum"mary, widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt text", name: "alt", widget: "string" }
      - label: "Video"
        name: "video"
        widget: "object"
        required: false
        fields:
          - { label: "Video", name: "src", widget: "video" }
          - { label: "Title", name: "title", widget: "string" }
      - label: "Related Guides"
        name: "relatedGuides"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: false,
            }
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string" }
      - label: "Related Stories"
        name: "relatedStories"
        widget: "list"
        required: false
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Slug", name: "slug", widget: "string" }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: false,
            }
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string" }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
