backend:
  name: git-gateway
  branch: chore/7-add-cms # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "public/images/uploads"

collections:
  - name: "story" # Used in routes, e.g., /admin/collections/blog
    label: "Story" # Used in the UI
    folder: "content/stories" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Location", name: "location", widget: "string" }
      - { label: "Featured Image", name: "images", widget: "image" }
      - { label: "Body", name: "body", widget: "markdown" }
