backend:
  name: git-gateway
  branch: chore/7-add-cms # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: public/images/uploads
i18n:
  structure: multiple_folders
  locales: [en, cy]
  default_locale: en

collections:
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    i18n: true
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Location", name: "location", widget: "string", i18n: true }
      - label: "Images"
        name: "images"
        widget: "list"
        fields:
          - { label: "Image", name: "src", widget: "image" }
          - { label: "Alt text", name: "alt", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "guides"
    label: "Guides"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Location", name: "location", widget: "string", i18n: true }
      - {
          label: "Summary",
          name: "summary",
          widget: "string",
          required: false,
          i18n: true,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - label: "Image"
        name: "image"
        widget: "object"
        required: false
        i18n: true 
        fields:
          - { label: "Image", name: "src", widget: "image"  }
          - { label: "Alt text", name: "alt", widget: "string", i18n: true }
      - label: "Video"
        name: "video"
        widget: "object"
        required: false
        i18n: true 
        fields:
          - { label: "Video", name: "src", widget: "video"  }
          - { label: "Title", name: "title", widget: "string", i18n: true }
      - label: "Related Guides"
        name: "relatedGuides"
        widget: "list"
        required: false
        i18n: true 
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Slug", name: "slug", widget: "string", i18n: true  }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: false,
              i18n: true,
            }
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            i18n: true 
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string", i18n: true }
      - label: "Related Stories"
        name: "relatedStories"
        widget: "list"
        required: false
        i18n: true 
        fields:
          - { label: "Title", name: "title", widget: "string", i18n: true }
          - { label: "Slug", name: "slug", widget: "string" }
          - {
              label: "Description",
              name: "description",
              widget: "string",
              required: false,
              i18n: true,
            }
          - label: "Image"
            name: "image"
            widget: "object"
            required: false
            fields:
              - { label: "Image", name: "src", widget: "image" }
              - { label: "Alt text", name: "alt", widget: "string", i18n: true }
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
