backend:
  name: github
  repo: geeksforsocialchange/teamwilder
  branch: main # Branch to update
publish_mode: editorial_workflow
media_folder: public/images/uploads
public_folder: /images/uploads
i18n:
  structure: multiple_folders
  locales: [en, cy]
  default_locale: en

collections:
  - name: "stories"
    label: "Stories"
    folder: "content/stories"
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}"
    i18n: true
    fields: # The fields for each document
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Who the story is about",
          name: "who",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Where it took place",
          name: "location",
          widget: "string",
          i18n: true,
        }
      - {
          label: "Postcode",
          hint: "Not displayed - for internal use",
          name: "postcode",
          required: false,
          widget: "string",
          i18n: true,
        }
      - label: "Images"
        name: "images"
        widget: "list"
        required: false
        i18n: true
        fields:
          - { label: "Image", name: "src", widget: "image", i18n: true }
          - { label: "Alt text", name: "alt", widget: "string", i18n: true }
          - {
              label: "Photo credit",
              name: "credit",
              widget: "string",
              required: false,
              i18n: true,
            }
          - {
              label: "Caption",
              name: "caption",
              widget: "string",
              required: false,
              i18n: true,
            }
      - {
          label: "Summary",
          hint: "Also used for SEO description",
          name: "summary",
          widget: "string",
          pattern: ["^.{50,160}$", "Must be between 50 and 160 characters"],
          i18n: true,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "guides"
    label: "Guides"
    folder: "content/guides"
    create: true
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Summary",
          name: "summary",
          widget: "string",
          pattern: ["^.{50,160}$", "Must be between 50 and 160 characters"],
          i18n: true,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
      - label: "Image"
        name: "image"
        widget: "object"
        i18n: true
        fields:
          - {
              label: "Image",
              name: "src",
              widget: "image",
              required: false,
              i18n: true,
            }
          - {
              label: "Alt text",
              name: "alt",
              widget: "string",
              required: false,
              i18n: true,
            }
          - {
              label: "Photo credit",
              name: "credit",
              widget: "string",
              required: false,
              i18n: true,
            }
      - label: "Video"
        name: "video"
        widget: "object"
        i18n: true
        fields:
          - {
              label: "URL",
              name: "src",
              widget: "string",
              required: false,
              i18n: true,
            }
          - {
              label: "Title",
              name: "title",
              widget: "string",
              required: false,
              i18n: true,
            }
      - label: "Related Guides"
        name: "relatedGuides"
        widget: "relation"
        collection: "guides"
        multiple: true
        search_fields: ["title", "summary"]
        value_field: "title"
        display_fields: ["title"]
        required: false
        i18n: false
      - label: "Related Stories"
        name: "relatedStories"
        widget: "relation"
        collection: "stories"
        multiple: true
        search_fields: ["title", "summary"]
        value_field: "title"
        display_fields: ["title"]
        required: false
        i18n: false
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: false
    slug: "{{slug}}"
    i18n: true
    fields:
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Summary",
          name: "summary",
          widget: "string",
          pattern: ["^.{50,160}$", "Must be between 50 and 160 characters"],
          i18n: true,
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
